# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 803f7ac40a4e998e732539110ccf90697c1b2f5df4171acff9313e902c4d4af1b1a5d0c789e4d9197cfde933d7356f453ab9d839fb9e7f35506cbecf61aa65ab

test:
  secret_key_base: 824ead69690b1ad38884f1f5baa73870a3a00cb315b9371832d73aa5f85e7af5d648d27e53e12a5fdd8f5fb769e3188dbc5d92a2c6bc711a229bdd2c25bc41a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
